/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 09 14:25:51 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.DequeNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DequeNode_ESTest extends DequeNode_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      DequeNode dequeNode0 = new DequeNode((-1));
  }

  @Test
  public void test1()  throws Throwable  {
      DequeNode dequeNode0 = new DequeNode();
  }
}
